version: '3'
services:
  db:
    image: mysql:5.5
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "radelement"
    volumes:
      - mysql-vol:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/srv/app
    ports:
      - "5000:80"
    depends_on:
      - db
    links:
      - db

volumes:
  mysql-vol: